[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
authors = ["tobi1805"]

[lib]
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
